- name: clone app repo
  git: repo='https://github.com/ohr486/phx-bench.git' dest='/usr/local/src/phx-bench'

- name: install hex
  shell: source /etc/profile.d/kerl.sh && export PATH=$PATH:/usr/local/bin && mix local.hex --force
  args:
    chdir: /usr/local/src/phx-bench/app

- name: install rebar
  shell: source /etc/profile.d/kerl.sh && export PATH=$PATH:/usr/local/bin && mix local.rebar --force
  args:
    chdir: /usr/local/src/phx-bench/app

- name: build apps
  shell: source /etc/profile.d/kerl.sh && export PATH=$PATH:/usr/local/bin && sh ./build.sh
  args:
    chdir: /usr/local/src/phx-bench/app
